var nock = require('nock');

before(function() {
    nock("http://www.site.com")
    .post("/auth/user")
    .times(Number.MAX_VALUE)
    .reply(200)
    .get("/newpath/users")
    .reply(200, "This is a new path for Users page.")
    .get("/users")
    .reply(200, "This is Users page.")
    .get("/users")
    .reply(200)
    .post("/admin")
    .reply(201)
    .get("/admin/Weto%20Olaguer")
    .reply(200)
    .put("/admin/1")
    .reply(200)
    .get("/admin?name=Towe%20Olaguer")
    .reply(200)
    .delete("/admin/1")
    .reply(200)
    .post("/files")
    .reply(201)
    .put("/files/1")
    .reply(200)
    .get("/uri/default")
    .reply(200, { uri : "/uri/default" })
    .post("/uri/default")
    .reply(201, { uri: "/uri/default" })
    .put("/uri/default/sample")
    .reply(200, { uri : "/uri/default" })
    .delete("/uri/default")
    .reply(200, { uri : "/uri/default" })
    .get("/uri/default")
    .reply(200, { uri : "/uri/default" })
    .get("/uri/get")
    .reply(200, { uri : "/uri/get" })
    .post("/uri/post")
    .reply(200, { uri : "/uri/post" })
    .put("/uri/put/sample")
    .reply(200, { uri : "/uri/put" })
    .delete("/uri/del")
    .reply(200, { uri : "/uri/del" });
});
